kuntavaalit tabs working
ruut975/paula-himanen pull request #10
Opened 2021-03-14 00:18 UTC by ruut975

2021-03-14 22:07 UTC, giograf commented on components/ElectionsIntro/ElectionsIntro.js
> +export default ElectionsIntro;
Check new lines in the end of files

2021-03-14 22:07 UTC, giograf commented on components/Tabs/Tab/Tab.js
> +
Redundant empty line.

2021-03-14 22:11 UTC, giograf commented on components/ThemeShort/ThemeShort.js
> +    image = <Image src={src} alt={alt} width={width} height={height} />;
Line 22 and 28 are the same, therefore they can be outside the if-else statement.

2021-03-14 22:13 UTC, giograf commented on components/ThemeShort/ThemeShort.js
> +    const width = firstImage.primary?.image.dimensions.width;
Best to add optional chaining to all items in if block. since if the code does not break on line 18, it still can on line 20.
I would also add optional chaining to default image "image" property.

2021-03-14 22:18 UTC, giograf commented on pages/kuntavaalit-2021/[[...uid]].js
> +    Prismic.Predicates.at("document.type", "default_image")
I think you need some kind of global settings document.
I don't think it is a good idea to create a default_image document, since it is hard to find in Prismic, it is best to create some kind of "Global Settings" or "Global Configuration" document and put default image as one of the settings.

2021-03-14 22:19 UTC, giograf commented on pages/teemat/[[...uid]].js
> +
Redundant empty line.

2021-03-14 22:20 UTC, giograf requested changes
Left few comments.

2021-03-15 09:52 UTC, ruut975 commented
#### 📝Changed routes:


| [**…vaalit-2021/\[\[...uid\]\]**](https://paula-himanen-q7702c9dk-ruut975.vercel.app/kuntavaalit-2021/[[...uid]]) | [**/teemat/\[\[...uid\]\]**](https://paula-himanen-q7702c9dk-ruut975.vercel.app/teemat/[[...uid]]) |
|:-:|:-:|
|<a href="https://paula-himanen-q7702c9dk-ruut975.vercel.app/kuntavaalit-2021/[[...uid]]"><img src="https://images.weserv.nl?url=https://s.microlink.io/3vPIfiFPo2hVWSV1fcfiwLMvP_c_.png&w=600" alt="Screenshot of /kuntavaalit-2021/[[...uid]]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/0jdmeRgUIix1chWOClznF2y_dtw_.png">(view full size)</a> |<a href="https://paula-himanen-q7702c9dk-ruut975.vercel.app/teemat/[[...uid]]"><img src="https://images.weserv.nl?url=https://s.microlink.io/QD3ml0QY0KklQWLi_syZiAgmuR0_.png&w=600" alt="Screenshot of /teemat/[[...uid]]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/yvtqY6MFXMhW98M7iCoLwvQeQzY_.png">(view full size)</a> |





1 deleted route:
- **/kuntavaalit-2021**

Commit adf8150a0e87f17db0d081b450a53d534232c802 (https://paula-himanen-q7702c9dk-ruut975.vercel.app).

2021-03-15 09:54 UTC, merged