Hero background image, title and description. Mobile navigation slide down menu fixed
ruut975/paula-himanen pull request #13
Opened 2021-03-16 21:41 UTC by ruut975

2021-03-16 22:35 UTC, giograf commented on UI/Backdrop/Backdrop.module.css
> +}
Check the missing empty lines at the end of files.

2021-03-16 22:42 UTC, giograf commented on components/Posts/PostShort/PostShort.js
> +  const title = RichText.asText(post.data.title) ?? 'Untitled'
Can you check if this works if post.data.title is not set?
?? operator will work if RichText.asText(post.data.title) is equal to null or undefined. However if it is a an empty string or 0 (a falsy value) it will not work. Then you need to use || operator that will work with all faulty values :)

2021-03-16 22:43 UTC, giograf commented on components/Summary/SummaryItem/SummaryItem.js
> +        <div className={styles.readMoreLink}>
Are those values available?
hoverGreen flexStart

2021-03-16 22:58 UTC, giograf requested changes
Few comments left.

2021-03-16 22:58 UTC, giograf commented on containers/Introduction/Introduction.js
> +      <ReadMoreLink path={readMorePath} className={styles.link} bold hoverGreen>
Are bold and hoverGreen properties used?

2021-03-16 22:58 UTC, giograf commented on containers/Header/Header.js
> +  let alt = null;
I think you can specify it using the following syntax:
`let alt, src`, the values will be eventually set anyway, so there is no need to see it to null initially.

2021-03-16 22:58 UTC, giograf commented on pages/eng/index.js
> +  const short = true;
Unused variable?

2021-03-16 22:58 UTC, giograf commented on pages/index.js
>        summaries: summaries ? summaries.results : [],
I think summaries and headers are not used in the file, so they can be removed?

2021-03-16 22:58 UTC, giograf commented on pages/teemat/[[...uid]].js
> +    const defaultBackground = headers[0].data.background_image;
I wonder what the headers object is supposed to contain apart from the default background.
It sounds that headers would be something that could go to the HEAD of the HTML or to header component (where we have menu and logo). The name is a bit confusing, so it might be worth renaming.

2021-03-17 07:43 UTC, ruut975 commented
#### 📝Changed routes:


| [**/blogi/\[uid\]**](https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/blogi/[uid]) | [**/blogi**](https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/blogi) |
|:-:|:-:|
|<a href="https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/blogi/[uid]"><img src="https://images.weserv.nl?url=https://s.microlink.io/gxnoaQvv2bULLwcpk9yG8G4TV8s_.png&w=600" alt="Screenshot of /blogi/[uid]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/u_7kvBdSsykU25kyCQgmL0rulog_.png">(view full size)</a> |<a href="https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/blogi"><img src="https://images.weserv.nl?url=https://s.microlink.io/sN4vum9ncEOlYbdM6QeAYvhbWUQ_.png&w=600" alt="Screenshot of /blogi" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/Z0mscAOe1pOPf9iRkijP_B1HFdQ_.png">(view full size)</a> |



| [**/eng**](https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/eng) | [**/**](https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/) |
|:-:|:-:|
|<a href="https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/eng"><img src="https://images.weserv.nl?url=https://s.microlink.io/XLsBtprGjPcyjKpfCYZ2LivlhLQ_.png&w=600" alt="Screenshot of /eng" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/kebUGm_Gzb__MwajvRDX10Bkfcs_.png">(view full size)</a> |<a href="https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/"><img src="https://images.weserv.nl?url=https://s.microlink.io/vPwrXzYx5ZPhD4Fb4Hk22jkAIj8_.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/xEU_yMZ0P7V1xy0EVa12xYt8DpE_.png">(view full size)</a> |



| [**…vaalit-2021/\[\[...uid\]\]**](https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/kuntavaalit-2021/[[...uid]]) | [**/paula**](https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/paula) |
|:-:|:-:|
|<a href="https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/kuntavaalit-2021/[[...uid]]"><img src="https://images.weserv.nl?url=https://s.microlink.io/AZ46jA4CjktD50fVuMY8O0kwSig_.png&w=600" alt="Screenshot of /kuntavaalit-2021/[[...uid]]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_mnrADQPI5kbbxQDWvSc6bV34to_.png">(view full size)</a> |<a href="https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/paula"><img src="https://images.weserv.nl?url=https://s.microlink.io/7i8vtTRsV5zOvXxhNvCJT4YFP2c_.png&w=600" alt="Screenshot of /paula" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/fwoNic40OK7O9bJnG7h5eRDyr6k_.png">(view full size)</a> |



And 1 other route:
- [**/teemat/\[\[...uid\]\]**](https://paula-himanen-gtg2mgrhl-ruut975.vercel.app/teemat/[[...uid]])



Commit 6f7bfe38d18be7cc0fe0d805e721a110f5057989 (https://paula-himanen-gtg2mgrhl-ruut975.vercel.app).

2021-03-17 07:50 UTC, ruut975 commented on components/Posts/PostShort/PostShort.js
> +  const title = RichText.asText(post.data.title) ?? 'Untitled'
I checked and it didn't work. I mean nothing was broken but it is good to show untitled instead of nothing. With OR it works correctly.

2021-03-17 07:53 UTC, ruut975 commented on components/Summary/SummaryItem/SummaryItem.js
> +        <div className={styles.readMoreLink}>
Yes, they are available and working

2021-03-17 07:54 UTC, ruut975 commented on containers/Introduction/Introduction.js
> +      <ReadMoreLink path={readMorePath} className={styles.link} bold hoverGreen>
yes, they are

2021-03-17 07:57 UTC, ruut975 commented on containers/Header/Header.js
> +  let alt = null;
ok 👍

2021-03-17 07:59 UTC, ruut975 commented on pages/index.js
>        summaries: summaries ? summaries.results : [],
they are all used in the file.

2021-03-17 08:08 UTC, ruut975 commented on pages/teemat/[[...uid]].js
> +    const defaultBackground = headers[0].data.background_image;
I will rename that object

2021-03-17 08:15 UTC, giograf approved these changes

2021-03-17 08:15 UTC, merged