Header
ruut975/paula-himanen pull request #2
Opened 2021-03-07 17:06 UTC by ruut975

2021-03-07 18:18 UTC, giograf requested changes

2021-03-07 18:18 UTC, giograf commented on UI/Backdrop/Backdrop.module.css
> +  z-index: 100;
This is good. I would also suggest using variables for z-index values like --global-z-index-backdrop. As an idea. Then when creating another overlapping element, you could see which value it should have based on the existing z-index variables (from the variable definition css file)

2021-03-07 18:18 UTC, giograf commented on UI/Modal/Modal.module.css
> +  z-index: 500;
Also possible variable use for z-index here.

2021-03-07 18:18 UTC, giograf commented on components/NavItems/NavItems.module.css
> +  z-index: 200;
A variable opportunity.

2021-03-07 18:18 UTC, giograf commented on components/NavItems/NavItems.module.css
> +/* desktop */
Desktop & Tablet

2021-03-07 18:18 UTC, giograf commented on components/NavItems/NavItems.module.css
> +    z-index: 500;
Z-index variable.

2021-03-07 18:18 UTC, giograf commented on components/NavItems/NavItems.module.css
> +  .close {
`.open, .close` - you can combine the two css rules.

2021-03-07 18:18 UTC, giograf commented on containers/Navbar/Navbar.js
> +    iconSrc = "/x-mark-icon.svg";
Here you could use one liner:
`iconSrc = showMenu ? ''one path"  : "another path"`

2021-03-07 18:18 UTC, giograf commented on containers/Navbar/Navbar.js
> +        <a href="#" className={styles.toggleNav}>
You should use a button tag, because this is not a link.

2021-03-07 18:18 UTC, giograf commented on containers/Navbar/Navbar.module.css
> +  z-index: 300;
Opportunity to use a variable.

2021-03-07 18:18 UTC, giograf commented on containers/Navbar/Navbar.module.css
> +    margin: 30px 20px 0 20px;
`margin: 30px 20px 0`would suffice.

2021-03-07 18:18 UTC, giograf commented on containers/Navbar/Navbar.module.css
> +  .navbarFlex {
Can be removed

2021-03-07 18:18 UTC, giograf commented on containers/Navbar/Navbar.module.css
> +@media (min-width: 1024px) {
Can be removed.

2021-03-07 18:18 UTC, giograf commented on containers/Navbar/Navbar.module.css
> +  margin: 6px 9px 0 9px;
`margin: 6px 9px 0`

2021-03-07 18:18 UTC, giograf commented on containers/Navbar/Navbar.module.css
> +  z-index: 500;
Z-index variable

2021-03-07 22:28 UTC, ruut975 commented on components/NavItems/NavItems.module.css
> +  .close {
ok

2021-03-07 23:15 UTC, merged

2021-03-08 18:55 UTC, giograf commented on components/NavItems/NavItems.js
> +
Remove empty line.